project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://Talha-Zaheer1.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: lumen
    toc: false
    code-fold: true
    code-summary: "Click to view code"
editor:
  mode: source
  
  